# Generated by Django 4.2.30 on 2026-09-22 16:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_columns", models.JSONField(blank=True, default=list)),
                ("event_columns", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shape",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("requested_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "requested_user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "-created_at"], name="logintoken_email_recent"
                    ),
                    models.Index(
                        fields=["expires_at", "consumed_at"], name="logintoken_sweep"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("matched_deterministic", "Matched deterministic"),
                            ("inferring", "Inferring"),
                            ("matched_inferred", "Matched inferred"),
                            ("no_match", "No match"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("decision", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True, related_name="action_jobs", to="app.event"
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_jobs",
                        to="app.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="OutreachRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("inference", "AI inference"),
                        ],
                        max_length=16,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                (
                    "inference_prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["owner", "enabled"], name="orule_owner_enabled"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="outreachrule",
            constraint=models.CheckConstraint(
                check=models.Q(("kind__in", ("deterministic", "inference"))),
                name="orule_kind_known",
            ),
        ),
        migrations.AddIndex(
            model_name="actionjob",
            index=models.Index(
                fields=["status", "created_at"], name="ajob_queue_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="actionjob",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        (
                            "queued",
                            "processing",
                            "matched_deterministic",
                            "inferring",
                            "matched_inferred",
                            "no_match",
                            "failed",
                        ),
                    )
                ),
                name="ajob_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("queued", "processing", "inferring"))
                ),
                fields=("lead",),
                name="ajob_one_open_per_lead",
            ),
        ),
    ]
