# Generated by Django 4.2.30 on 2026-09-16 16:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]*$",
                                "Use a snake_case key: lowercase letters, digits and underscores, starting with a letter (e.g. 'reward_power_user').",
                            )
                        ],
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="OutreachRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("inference", "AI inference"),
                        ],
                        max_length=16,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                (
                    "inference_prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rules",
                        to="app.actiontype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-weight", "id"],
                "indexes": [
                    models.Index(
                        fields=["owner", "enabled"], name="orule_owner_enabled"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="outreachrule",
            constraint=models.CheckConstraint(
                check=models.Q(("kind__in", ("deterministic", "inference"))),
                name="orule_kind_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="outreachrule",
            constraint=models.CheckConstraint(
                check=models.Q(("weight__in", (1, 2, 3))), name="orule_weight_1_to_3"
            ),
        ),
        migrations.AddConstraint(
            model_name="actiontype",
            constraint=models.UniqueConstraint(
                fields=("owner", "key"), name="atype_one_key_per_owner"
            ),
        ),
    ]
