# Generated by Django 4.2.30 on 2026-09-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_evm_receipts"),
        ("app", "0013_address_fields"),
    ]

    operations = []
