# Generated by Django 4.2.30 on 2026-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_rule_tag_glyph_sentence_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="symbol",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
