/**
 * The demo's stand-in for the LLM proposal reads the prototype's example sentences
 * into the prototype's trees. The oracle was generated by running the prototype's own
 * parser (prototype/src/engine.js) and mapping its trees to the contract's names.
 */
import assert from 'node:assert/strict';
import { test } from 'node:test';

import { ApiError } from '../src/api/client.ts';
import { DemoConsoleApi } from '../src/console/api/demo/DemoConsoleApi.ts';
import oracle from './fixtures/parser-oracle.json' with { type: 'json' };

const api = new DemoConsoleApi({ latency: [0, 0] });

for (const expected of oracle) {
  test(`"${expected.sentence}" is wired as the prototype wired it`, async () => {
    if (expected.condition === null) {
      await assert.rejects(api.propose(expected.sentence), (error: unknown) => error instanceof ApiError && error.status === 422);
      return;
    }
    const proposal = await api.propose(expected.sentence);
    assert.deepEqual(proposal.condition, expected.condition);
    assert.equal(proposal.name, expected.name);
    assert.deepEqual(proposal.understood, expected.understood);
    assert.equal(proposal.tag, expected.tag);
  });
}

test('comparison symbols read as their operators', async () => {
  const at = async (sentence: string) => {
    const proposal = await api.propose(sentence);
    return (proposal.condition as { children: { operator: string; value: unknown }[] }).children.at(-1);
  };
  assert.deepEqual(await at('USDT transfers >= 1.5k'), { id: null, type: 'comparison', source: 'token_transfer', field: 'amount', operator: 'gte', value: '1500' });
  assert.equal((await at('USDC transfers < 250'))?.operator, 'lt');
  assert.equal((await at('USDC transfers <= 0.5'))?.value, '0.5');
});
